version: '3.3'

services:
  intruders:
    container_name: intruders
    build: .
    env_file:
      - .env
    volumes:
      - ./log:/code/log
      - ./shots:/code/shots
volumes:
  intruders_volume:
